### ISSUE TITLE
Warning for uninitialized min_intron_size variable.

### ISSUE THREAD

**Issue by akhtar4ever** [konradjk/loftee#21] opened 2017-08-14 08:45 UTC
Hi,

I am getting below warning while using Lof tool not sure if the output will be not as per the expectation:

Use of uninitialized value in numeric lt (<) at /home/veptools/.vep/Plugins/LoF.pm line 285.
Use of uninitialized value in numeric lt (<) at /home/veptools/.vep/Plugins/LoF.pm line 285.
Use of uninitialized value $min_intron_size in numeric lt (<) at /home/veptools/.vep/Plugins/LoF.pm line 322.
Use of uninitialized value $min_intron_size in numeric lt (<) at /home/veptools/.vep/Plugins/LoF.pm line 322.

Using the tool as :
--plugin LoF,human_ancestor_fa:/home/veptools/.vep/human_ancestor.fa along with other vep parameters.

It appears that the $min_intron_size variable is not getting populated.

Please guide me.

Thanks in advance.

**Comment by birndle** [comment] 2017-08-15 16:17
Hello,

Thank you for pointing this out. There was a bug in the code where min_intron_size was not receiving a default value. It should be fixed now if you pull down the repo. Let us know if you continue to have issues.

- Dan

**Comment by akhtar4ever** [comment] 2017-09-01 07:08
Thanks a  lot Dan,

I would check it.


Have not been working due to some serious illness.

Will update you later.

Thanks and regards
Aktar Alam

On 15-Aug-2017 9:47 PM, "Daniel Birnbaum" <notifications@github.com> wrote:

Hello,

Thank you for pointing this out. There was a bug in the code where
min_intron_size was not receiving a default value. It should be fixed now
if you pull down the repo. Let us know if you continue to have issues.

   - Dan

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/konradjk/loftee/issues/21#issuecomment-322514452>, or mute
the thread

**Comment by akhtar4ever** [comment] 2017-10-11 07:47
Thanks Dan,

I checked it, its not flagging the old error but a new warning is being flagged.


_Use of uninitialized value $faidx in split at /home/veptools/.vep/Plugins/LoF.pm line 492.
Use of uninitialized value $faidx in split at /home/veptools/.vep/Plugins/LoF.pm line 492.
Use of uninitialized value $faidx in split at /home/veptools/.vep/Plugins/LoF.pm line 492._

Also the execution is not getting completed as its flagging memory error.


**

_> _Argument "" isn't numeric in addition (+) at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm line 211, <__ANONIO__> line 53828.
> Argument "" isn't numeric in addition (+) at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm line 211, <__ANONIO__> line 53828.
> Argument "" isn't numeric in addition (+) at /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseCacheVariation.pm line 211, <__ANONIO__> line 53828.
> 
> -------------------- EXCEPTION --------------------
> MSG: ERROR: Cannot allocate memory
> STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::BaseSerialized::deserialize_from_file_storable /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseSerialized.pm:140
> STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::BaseSerialized::deserialize_from_file /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseSerialized.pm:103
> STACK Bio::EnsEMBL::VEP::AnnotationSource::Cache::BaseSerialized::get_features_by_regions_uncached /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource/Cache/BaseSerialized.pm:261
> STACK Bio::EnsEMBL::VEP::AnnotationSource::get_all_features_by_InputBuffer /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationSource.pm:134
> STACK Bio::EnsEMBL::VEP::AnnotationType::Transcript::annotate_InputBuffer /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/AnnotationType/Transcript.pm:104
> STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:366
> STACK Bio::EnsEMBL::VEP::Runner::next_output_line /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:328
> STACK Bio::EnsEMBL::VEP::Runner::run /usr/local/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:187
> STACK toplevel /usr/local/ensembl-vep/vep:211__

**

Please guide and provide your inputs.

**Note: System I am using has an i5  processor with 32GB RAM.**

**Comment by akhtar4ever** [comment] 2018-03-28 07:23
Hi konradjk,

Any guidance?

**Comment by konradjk** [comment] 2018-03-28 12:25
The warning (I think) is ok, but in any case, can't diagnose that until the run completes.

As to the memory error, this looks more like a VEP issue rather than LOFTEE, so I would contact the VEP folks to try to figure that out. One thing you could do is split up your VCF file and annotate them separately. But this looks like more of a fundamental issue, so might be better to figure out the root cause.

**Comment by konradjk** [comment] 2019-02-07 15:39
As this appears to be an issue with VEP not specifically LOFTEE, I'm going to close this for now.

**Closed by konradjk** 2019-02-07 15:39 UTC
