### ISSUE TITLE
Use of uninitialized value $number_of_exons 

### ISSUE THREAD

**Issue by zhouhufeng** [konradjk/loftee#36] opened 2018-11-06 16:35 UTC
I kept having this error for a while, and wondering how can I fix it? 

Use of uninitialized value $number_of_exons in subtraction (-) at /n/home05/zhouhufeng/.vep/Plugins/LoF.pm line 546, <__ANONIO__> line

**Comment by konradjk** [comment] 2019-02-07 15:30
Duplicate of #35

**Closed by konradjk** 2019-02-07 15:30 UTC
